import { LegalPage } from '../components/LegalPage'

const List = ({ items }: { items: string[] }) => <ul className="space-y-2">{items.map(item => <li key={item} className="flex gap-3"><span className="mt-3 size-1.5 shrink-0 rounded-full bg-brand-red" />{item}</li>)}</ul>

export function PrivacyPolicyPage() {
  return <LegalPage eyebrow="Protection des données" title="Politique de confidentialité" introduction="La présente politique de confidentialité décrit la manière dont Taxi-Lux SPRL collecte, utilise et protège les données personnelles des utilisateurs du site web et de l’application Taxi-Lux, conformément au Règlement Général sur la Protection des Données (RGPD)." sections={[
    { title: 'Responsable du traitement', content: <address className="not-italic"><strong className="text-navy">Taxi-Lux SPRL</strong><br />Grote Daalstraat 32<br />1930 Zaventem<br />Belgique<br /><br />Numéro d’entreprise : <strong className="text-navy">BE0457471103</strong></address> },
    { title: 'Données collectées', content: <><p>Dans le cadre de l’utilisation du site web et de l’application Taxi-Lux, les données suivantes peuvent être collectées :</p><List items={['Informations d’identification : prénom, nom', 'Coordonnées : adresse email, numéro de téléphone', 'Données de compte : identifiant utilisateur', 'Données de trajet : points de départ et d’arrivée, historique des trajets', 'Données techniques : type d’appareil, système d’exploitation, logs techniques', 'Données de localisation, uniquement lorsque nécessaire au fonctionnement du service']} /><p>Aucune donnée inutile ou excessive n’est collectée.</p></> },
    { title: 'Finalités du traitement', content: <><p>Les données personnelles sont utilisées uniquement pour :</p><List items={['Fournir et gérer les services de transport via l’application', 'Permettre la réservation et la gestion des trajets', 'Assurer la sécurité et le bon fonctionnement de l’application', 'Améliorer l’expérience utilisateur', 'Communiquer avec l’utilisateur en cas de besoin : support et informations liées au service']} /><p>Les données ne sont jamais utilisées à des fins commerciales non liées au service.</p></> },
    { title: 'Base légale', content: <><p>Le traitement des données repose sur :</p><List items={['L’exécution du service demandé par l’utilisateur', 'Le consentement de l’utilisateur lorsque requis', 'Les obligations légales applicables']} /></> },
    { title: 'Partage des données', content: <><p>Les données personnelles ne sont ni vendues, ni louées à des tiers.</p><p>Elles peuvent être partagées uniquement avec :</p><List items={['Des prestataires techniques nécessaires au fonctionnement de l’application : hébergement et services techniques', 'Des autorités légales si la loi l’exige']} /><p>Tous les partenaires respectent les obligations du RGPD.</p></> },
    { title: 'Conservation des données', content: <p>Les données sont conservées uniquement pendant la durée nécessaire aux finalités pour lesquelles elles ont été collectées, sauf obligation légale contraire.</p> },
    { title: 'Droits des utilisateurs', content: <><p>Conformément au RGPD, chaque utilisateur dispose des droits suivants :</p><List items={["Droit d’accès à ses données", 'Droit de rectification', 'Droit de suppression', 'Droit de limitation du traitement', "Droit d’opposition", 'Droit à la portabilité des données']} /><p>L’utilisateur peut supprimer son compte à tout moment directement depuis l’application, entraînant la suppression ou l’anonymisation de ses données, sauf obligation légale de conservation.</p></> },
    { title: 'Sécurité', content: <p>Taxi-Lux met en œuvre des mesures techniques et organisationnelles appropriées afin de protéger les données personnelles contre tout accès non autorisé, perte ou divulgation.</p> },
    { title: 'Cookies', content: <><p>Le site web peut utiliser des cookies techniques strictement nécessaires à son bon fonctionnement.</p><p>Aucun cookie publicitaire ou de tracking n’est utilisé sans le consentement préalable de l’utilisateur.</p></> },
    { title: 'Modifications', content: <p>Cette politique de confidentialité peut être mise à jour à tout moment afin de rester conforme aux évolutions légales ou techniques. La version la plus récente est toujours disponible sur le site.</p> },
    { title: 'Contact', content: <p>Pour toute question relative à la protection des données personnelles, l’utilisateur peut contacter Taxi-Lux via les coordonnées indiquées sur le site.</p> },
  ]} />
}
