import { LegalPage } from '../components/LegalPage'

const List = ({ items }: { items: string[] }) => <ul className="space-y-2">{items.map(item => <li key={item} className="flex gap-3"><span className="mt-3 size-1.5 shrink-0 rounded-full bg-brand-red" />{item}</li>)}</ul>

export function TermsPage() {
  return <LegalPage eyebrow="Conditions d’utilisation" title="Conditions Générales d’Utilisation" introduction="Les présentes Conditions Générales d’Utilisation (ci-après « CGU ») ont pour objet de définir les modalités d’accès et d’utilisation du site web et de l’application mobile Taxi-Lux, édités par Taxi-Lux SPRL. L’utilisation du site ou de l’application implique l’acceptation pleine et entière des présentes CGU." sections={[
    { title: 'Éditeur de la Plateforme', content: <address className="not-italic"><strong className="text-navy">Taxi-Lux SPRL</strong><br />Grote Daalstraat 32<br />1930 Zaventem<br />Belgique<br /><br />Numéro d’entreprise : <strong className="text-navy">BE0457471103</strong></address> },
    { title: 'Champ d’application', content: <><p>Les présentes CGU s’appliquent :</p><List items={['Au site internet Taxi-Lux, accessible au public', 'À l’application mobile Taxi-Lux, destinée aux utilisateurs du service de transport']} /><p>Elles encadrent l’ensemble des interactions entre l’utilisateur et Taxi-Lux, qu’elles aient lieu via le site ou l’application.</p></> },
    { title: 'Objet de la Plateforme', content: <><p>La Plateforme Taxi-Lux a pour objet :</p><List items={['La présentation et la promotion des services Taxi-Lux', 'La création et la gestion de comptes utilisateurs', 'La réservation et la gestion de services de transport via l’application mobile']} /><p>Le site internet a un rôle principalement informatif, tandis que les services opérationnels sont accessibles via l’application mobile.</p></> },
    { title: 'Accès et création de compte', content: <><p>L’accès à certaines fonctionnalités de la Plateforme nécessite la création d’un compte utilisateur.</p><p>L’utilisateur s’engage à :</p><List items={['Fournir des informations exactes et à jour', 'Préserver la confidentialité de ses identifiants', 'Ne pas créer de compte frauduleux ou usurper l’identité d’un tiers']} /><p>Taxi-Lux se réserve le droit de suspendre ou supprimer tout compte en cas d’usage abusif ou non conforme.</p></> },
    { title: 'Utilisation de la Plateforme', content: <><p>L’utilisateur s’engage à utiliser la Plateforme :</p><List items={['Dans le respect des lois et règlements en vigueur', 'À des fins personnelles et légitimes', 'Sans porter atteinte au bon fonctionnement du service']} /><p>Toute tentative de fraude, d’accès non autorisé ou de perturbation du service est strictement interdite.</p></> },
    { title: 'Responsabilité', content: <><p>Taxi-Lux met en œuvre les moyens raisonnables pour assurer l’accessibilité et le bon fonctionnement de la Plateforme.</p><p>Toutefois, Taxi-Lux ne saurait être tenu responsable notamment :</p><List items={['Des interruptions temporaires liées à la maintenance ou à des incidents techniques', 'Des retards ou perturbations dus à des facteurs externes : trafic, conditions météorologiques ou événements imprévus', 'De l’utilisation non conforme de la Plateforme par l’utilisateur']} /></> },
    { title: 'Données personnelles', content: <p>Les données personnelles des utilisateurs sont traitées conformément à la Politique de confidentialité, applicable au site internet et à l’application mobile. L’utilisateur peut notamment exercer ses droits RGPD et supprimer son compte à tout moment depuis l’application.</p> },
    { title: 'Propriété intellectuelle', content: <><p>L’ensemble des contenus présents sur la Plateforme (textes, visuels, logos, interface, structure, code) est protégé par les droits de propriété intellectuelle.</p><p>Toute reproduction ou exploitation non autorisée est interdite.</p></> },
    { title: 'Suppression de compte', content: <><p>L’utilisateur peut supprimer son compte à tout moment via l’application mobile. La suppression entraîne :</p><List items={['La désactivation immédiate du compte', 'La suppression ou l’anonymisation des données personnelles, sauf obligation légale de conservation']} /></> },
    { title: 'Modification des CGU', content: <p>Taxi-Lux se réserve le droit de modifier les présentes CGU à tout moment. Les utilisateurs seront informés de toute modification substantielle via la Plateforme. La version en vigueur est celle publiée sur le site internet.</p> },
    { title: 'Droit applicable', content: <p>Les présentes CGU sont régies par le droit belge. En cas de litige, les tribunaux compétents seront ceux du ressort du siège social de Taxi-Lux SPRL.</p> },
  ]} />
}
